feat(aws/work-machine): aws workmachines
- workspace template updates

diff --git a/workspace-templates/images/vscode-start b/workspace-templates/images/vscode-start
--- a/workspace-templates/images/vscode-start
+++ b/workspace-templates/images/vscode-start
@@ -1,11 +1,12 @@
+#!/usr/bin/env bash
 set -e
 if [ -f "/env/.connected_env" ]; then
-cat > /tmp/resolv.conf <<EOF
+  cat >/tmp/resolv.conf <<EOF
 search env-$(cat /env/.connected_env).svc.cluster.local svc.cluster.local cluster.local
 nameserver 10.43.0.10
 options ndots:5
 EOF
-sudo cp /tmp/resolv.conf /etc/resolv.conf
+  sudo cp /tmp/resolv.conf /etc/resolv.conf
 fi
 
 export HOST=box
@@ -15,9 +16,13 @@ if [ -f "/env/.env" ]; then
   sudo bash -c "cat /env/.env >> /etc/environment"
 fi
 
-cd $KL_WORKSPACE
+[ -z "$KL_WORKSPACE_DIR" ] && echo "env var: KL_WORKSPACE_DIR is missing" && exit 1
+[ -z "$KL_WORKSPACE" ] && echo "env var: KL_WORKSPACE is missing" && exit 1
 
-/code/code tunnel --name $KL_WORKSPACE_NAME --cli-data-dir /home/kl/.tunnels/$KL_WORKSPACE_NAME --accept-server-license-terms &
+cd "$KL_WORKSPACE_DIR"
+
+mkdir -p "/home/kl/.tunnels/$KL_WORKSPACE"
+/code/code tunnel --name "$KL_WORKSPACE" --cli-data-dir "/home/kl/.tunnels/$KL_WORKSPACE" --accept-server-license-terms &
 
 pid=$!
 trap "kill -9 $pid" TERM INT EXIT
